#function description: 
#procedure name: p_dm_orderdaycalltip
#creator:MARS
#created:
#!/bin/bash
#today date
V_DATE=$1
#
if [ -z ${V_DATE} ];then
        V_DATE=`date +%Y-%m-%d`
fi

#yesterday data partition
V_PARYEAR=`date --date="$V_DATE-1 day" +%Y`
V_PARMONTH=`date --date="$V_DATE-1 day" +%m`
V_PARDAY=`date --date="$V_DATE-1 day" +%d`
V_PARYESTERDAY=`date --date="$V_DATE-1 day" +%Y%m%d`
#today,yesterday,7 day  ago,30 days ago,2 days ago  date
V_TODAY=`date -d $V_DATE "+%Y-%m-%d"`
V_YESTERDAY=`date --date="$V_DATE-1 day" +%Y-%m-%d`
V_7DAYS=`date --date="$V_DATE-7 day" +%Y-%m-%d`
V_WEEK=`date --date="$V_DATE-7 day" +%Y-%m-%d`
V_THREEWEEKS=`date --date="$V_DATE-21 day" +%Y-%m-%d`
V_THREEMONTHS=`date --date="$V_DATE-90 day" +%Y-%m-%d`
V_SIXMONTHS=`date --date="$V_DATE-180 day" +%Y-%m-%d`
V_15DAYS=`date --date="$V_DATE-15 day" +%Y-%m-%d`
V_30DAYS=`date --date="$V_DATE-30 day" +%Y-%m-%d`
V_TWODAYS=`date --date="$V_DATE-2 day" +%Y-%m-%d`
#30 days ago, 2 days ago data partition 
V_PAR7DAYS=`date --date="$V_DATE-7 day" +%Y%m%d`
V_PAR15DAYS=`date --date="$V_DATE-15 day" +%Y%m%d`
V_PAR30DAYS=`date --date="$V_DATE-30 day" +%Y%m%d`
V_PAR2DAYS=`date --date="$V_DATE-2 day" +%Y%m%d`
/home/xiaoju/hive-0.10.0/bin/hive -e"use app;
INSERT OVERWRITE TABLE ORDERDAYCALLTIP PARTITION(YEAR='$V_PARYEAR',MONTH='$V_PARMONTH',DAY='$V_PARDAY')
SELECT 0,
       '$V_YESTERDAY',
	    M.AREA,
	    M.CHANNEL,
		(CASE WHEN A.ORDERDAYCALLNUM IS NOT NULL THEN CAST(A.ORDERDAYCALLNUM AS INT) ELSE 0 END) ORDERDAYCALLNUM,
		(CASE WHEN A.ORDERDAYCALLREPLYNUM IS NOT NULL THEN CAST(A.ORDERDAYCALLREPLYNUM AS INT) ELSE 0 END) ORDERDAYCALLREPLYNUM,
		(CASE WHEN A.ORDERDAYCALLREPLYNUM IS NOT NULL AND A.ORDERDAYCALLNUM IS NOT NULL AND A.ORDERDAYCALLNUM<>0 
				THEN ROUND(A.ORDERDAYCALLREPLYNUM/A.ORDERDAYCALLNUM,3) 
			ELSE 0.000 END) ORDERDAYCALLSUCCRATE,
		(CASE WHEN A.ORDERDAYTIPNUM IS NOT NULL THEN CAST(A.ORDERDAYTIPNUM AS INT) ELSE 0 END) ORDERDAYTIPNUM,
		(CASE WHEN A.ORDERDAYTIPREPLYNUM IS NOT NULL THEN CAST(A.ORDERDAYTIPREPLYNUM AS INT) ELSE 0 END) ORDERDAYTIPREPLYNUM,
		(CASE WHEN A.ORDERDAYTIPREPLYNUM IS NOT NULL AND A.ORDERDAYTIPNUM IS NOT NULL AND A.ORDERDAYTIPNUM<>0 
		        THEN ROUND(A.ORDERDAYTIPREPLYNUM/A.ORDERDAYTIPNUM,3) 
			ELSE 0.000 END) ORDERDAYTIPSUCCRATE,
		(CASE WHEN A.ORDERDAYTIP0YUANNUM IS NOT NULL THEN CAST(A.ORDERDAYTIP0YUANNUM AS INT) ELSE 0 END) ORDERDAYTIP0YUANNUM,
		(CASE WHEN A.ORDERDAYTIP0YUANREPLYNUM IS NOT NULL THEN CAST(A.ORDERDAYTIP0YUANREPLYNUM AS INT) ELSE 0 END) ORDERDAYTIP0YUANREPLYNUM,
		(CASE WHEN A.ORDERDAYTIP0YUANREPLYNUM IS NOT NULL AND A.ORDERDAYTIP0YUANNUM IS NOT NULL AND A.ORDERDAYTIP0YUANNUM<>0 
				THEN ROUND(A.ORDERDAYTIP0YUANREPLYNUM/A.ORDERDAYTIP0YUANNUM,3) 
			ELSE 0.000 END) ORDERDAYTIP0YUANSUCCRATE,
		(CASE WHEN A.ORDERDAYTIP5YUANNUM IS NOT NULL THEN CAST(A.ORDERDAYTIP5YUANNUM AS INT) ELSE 0 END) ORDERDAYTIP5YUANNUM,
		(CASE WHEN A.ORDERDAYTIP5YUANREPLYNUM IS NOT NULL THEN CAST(A.ORDERDAYTIP5YUANREPLYNUM AS INT) ELSE 0 END) ORDERDAYTIP5YUANREPLYNUM,
		(CASE WHEN A.ORDERDAYTIP5YUANREPLYNUM IS NOT NULL AND A.ORDERDAYTIP5YUANNUM IS NOT NULL AND A.ORDERDAYTIP5YUANNUM<>0 
				THEN ROUND(A.ORDERDAYTIP5YUANREPLYNUM/A.ORDERDAYTIP5YUANNUM,3) 
			ELSE 0.000 END) ORDERDAYTIP5YUANSUCCRATE,
		(CASE WHEN A.ORDERDAYTIP10YUANNUM IS NOT NULL THEN CAST(A.ORDERDAYTIP10YUANNUM AS INT) ELSE 0 END) ORDERDAYTIP10YUANNUM,
		(CASE WHEN A.ORDERDAYTIP10YUANREPLYNUM IS NOT NULL THEN CAST(A.ORDERDAYTIP10YUANREPLYNUM AS INT) ELSE 0 END) ORDERDAYTIP10YUANREPLYNUM,
		(CASE WHEN A.ORDERDAYTIP10YUANREPLYNUM IS NOT NULL AND A.ORDERDAYTIP10YUANNUM IS NOT NULL AND A.ORDERDAYTIP10YUANNUM<>0 
				THEN ROUND(A.ORDERDAYTIP10YUANREPLYNUM/A.ORDERDAYTIP10YUANNUM,3) 
			ELSE 0.000 END) ORDERDAYTIP10YUANSUCCRATE,
		(CASE WHEN A.ORDERDAYTIP20YUANNUM IS NOT NULL THEN CAST(A.ORDERDAYTIP20YUANNUM AS INT) ELSE 0 END) ORDERDAYTIP20YUANNUM,
		(CASE WHEN A.ORDERDAYTIP20YUANREPLYNUM IS NOT NULL THEN CAST(A.ORDERDAYTIP20YUANREPLYNUM AS INT) ELSE 0 END) ORDERDAYTIP20YUANREPLYNUM,
		(CASE WHEN A.ORDERDAYTIP20YUANREPLYNUM IS NOT NULL AND A.ORDERDAYTIP20YUANNUM IS NOT NULL AND A.ORDERDAYTIP20YUANNUM<>0 
				THEN ROUND(A.ORDERDAYTIP20YUANREPLYNUM/A.ORDERDAYTIP20YUANNUM,3) 
			ELSE 0.000 END) ORDERDAYTIP20YUANSUCCRATE	   
  FROM PDW.PASSENGER_AREA_CHANNEL M
LEFT OUTER JOIN
(  
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CAST(CHANNEL AS INT) END) CHANNEL,
	   ORDERDAYCALLNUM,
	   ORDERDAYCALLREPLYNUM,
	   ORDERDAYTIPNUM,
	   ORDERDAYTIPREPLYNUM,
	   ORDERDAYTIP0YUANNUM,
	   ORDERDAYTIP0YUANREPLYNUM,
	   ORDERDAYTIP5YUANNUM,
	   ORDERDAYTIP5YUANREPLYNUM,
	   ORDERDAYTIP10YUANNUM,
	   ORDERDAYTIP10YUANREPLYNUM,
	   ORDERDAYTIP20YUANNUM,
	   ORDERDAYTIP20YUANREPLYNUM
  FROM  (SELECT AREA,
			   (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END) CHANNEL,
			   SUM(CALLCOUNT) ORDERDAYCALLNUM,
			   SUM(CASE WHEN STATUS >=1  AND STATUS <=4 AND DRIVERID > 0 THEN 1
					  ELSE 0
					  END) ORDERDAYCALLREPLYNUM,
			   SUM(CASE WHEN TIP>0 THEN 1
					 ELSE 0
					 END) ORDERDAYTIPNUM,
			   SUM(CASE WHEN TIP >0 AND STATUS >=1  AND STATUS <=4 AND DRIVERID IS NOT NULL THEN 1
					 ELSE 0
					 END) ORDERDAYTIPREPLYNUM,
			   SUM(CASE WHEN TIP=0 THEN 1
					 ELSE 0
					 END) ORDERDAYTIP0YUANNUM,
			   SUM(CASE WHEN TIP =0 AND STATUS >=1  AND STATUS <=4 AND DRIVERID IS NOT NULL THEN 1
					 ELSE 0
					 END) ORDERDAYTIP0YUANREPLYNUM,	
			   SUM(CASE WHEN TIP=5 THEN 1
					 ELSE 0
					 END) ORDERDAYTIP5YUANNUM,
			   SUM(CASE WHEN TIP =5 AND STATUS >=1  AND STATUS <=4 AND DRIVERID IS NOT NULL THEN 1
					 ELSE 0
					 END) ORDERDAYTIP5YUANREPLYNUM,				 	
			   SUM(CASE WHEN TIP=10 THEN 1
					 ELSE 0
					 END) ORDERDAYTIP10YUANNUM,
			   SUM(CASE WHEN TIP =10 AND STATUS >=1  AND STATUS <=4 AND DRIVERID IS NOT NULL THEN 1
					 ELSE 0
					 END) ORDERDAYTIP10YUANREPLYNUM,
			   SUM(CASE WHEN TIP=20 THEN 1
					 ELSE 0
					 END) ORDERDAYTIP20YUANNUM,
			   SUM(CASE WHEN TIP =20 AND STATUS >=1  AND STATUS <=4 AND DRIVERID IS NOT NULL THEN 1
					 ELSE 0
					 END) ORDERDAYTIP20YUANREPLYNUM
		  FROM PDW.DW_ORDER
		 WHERE YEAR='$V_PARYEAR'
		   AND MONTH='$V_PARMONTH'
		   AND DAY='$V_PARDAY'
		   AND CREATETIME >= '$V_YESTERDAY' 
		   AND CREATETIME < '$V_TODAY'
		GROUP BY AREA,
				 (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END)    
		GROUPING SETS (AREA,
						 (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
							WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
							WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
							WHEN CHANNEL = 1101 THEN 5
							WHEN CHANNEL = 1102 THEN 6
							WHEN CHANNEL >= 10000 THEN 8
							WHEN CHANNEL >= 1000 THEN 7
							ELSE 2 
							END),
						(AREA,
						 (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
							WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
							WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
							WHEN CHANNEL = 1101 THEN 5
							WHEN CHANNEL = 1102 THEN 6
							WHEN CHANNEL >= 10000 THEN 8
							WHEN CHANNEL >= 1000 THEN 7
							ELSE 2 
							END)),
						())
		) D
) A
ON(M.AREA=A.AREA AND M.CHANNEL=A.CHANNEL)
;"
/home/xiaoju/hadoop-1.0.4/bin/hadoop fs -touchz /user/xiaoju/data/bi/app/orderdaycalltip/$V_PARYEAR/$V_PARMONTH/$V_PARDAY/_SUCCESS