#function description:
# 1.num of people who send item
# 2.the percentage of people who send item
# 3.send small item num
# 4.the average of small item by per people send
# 5.left item num
# 6.people share item first time
# 7.people who do not share item
# 8.the percentage of people who do not share item
# 9.item num for people who do not share   

#procedure name: P_DM_wechat_senditem_day
#creator: mayiming
#created:
#!/bin/bash
#today date
V_DATE=$1
#
if [ -z ${V_DATE} ];then
        V_DATE=`date +%Y-%m-%d`
fi
#
#yesterday data partition
V_PARYEAR=`date --date="$V_DATE-1 day" +%Y`
V_PARMONTH=`date --date="$V_DATE-1 day" +%m`
V_PARDAY=`date --date="$V_DATE-1 day" +%d`
V_PARYESTERDAY=`date --date="$V_DATE-1 day" +%Y%m%d`

#yesterday date 
V_YESTERDAY=`date --date="$V_DATE-1 day" +%Y-%m-%d`

/home/xiaoju/hive-0.10.0/bin/hive -e"use app;
ALTER TABLE WECHAT_SENDITEM_DAY ADD IF NOT EXISTS PARTITION (YEAR = '$V_PARYEAR',MONTH = '$V_PARMONTH',DAY = '$V_PARDAY') LOCATION '$V_PARYEAR/$V_PARMONTH/$V_PARDAY';
INSERT OVERWRITE TABLE WECHAT_SENDITEM_DAY PARTITION(YEAR='$V_PARYEAR',MONTH='$V_PARMONTH',DAY='$V_PARDAY')
SELECT 0 STATID,
       '${V_PARYEAR}-${V_PARMONTH}-${V_PARDAY}' STATDATE,
       A.AREA,
       0 CHANNEL,
       CASE WHEN B.PHONENUM IS NULL THEN CAST('0' AS BIGINT)  ELSE B.PHONENUM END,
       CASE WHEN B.PHONENUM IS NULL THEN 0.0 ELSE ROUND(B.PHONENUM/A.PHONENUM,3) END,
       CASE WHEN B.CNT_ITEMS_NUM IS NULL THEN CAST('0' AS BIGINT) ELSE B.CNT_ITEMS_NUM END,
       CASE WHEN B.CNT_ITEMS_RATE IS NULL THEN 0.0 ELSE B.CNT_ITEMS_RATE END,
       CASE WHEN B.LEFT_ITEMS_NUM IS NULL THEN CAST('0' AS BIGINT) ELSE B.LEFT_ITEMS_NUM END,
       CASE WHEN D.PHONENUM IS NULL THEN CAST('0' AS BIGINT)  ELSE D.PHONENUM END,
       CASE WHEN C.PHONENUM IS NULL THEN CAST('0' AS BIGINT) ELSE C.PHONENUM END,
       CASE WHEN C.PHONENUM IS NULL THEN 0.0 ELSE ROUND(C.PHONENUM/A.PHONENUM,3) END,
       CASE WHEN C.CNT_ITEMS_NUM IS NULL THEN CAST('0' AS BIGINT) ELSE C.CNT_ITEMS_NUM END
FROM 
(SELECT CASE WHEN AREA is NULL THEN '10000' ELSE AREA END AREA,
        COUNT(DISTINCT PHONE) PHONENUM 
 FROM PDW.WX_R_LIST_INFO 
 WHERE YEAR = '$V_PARYEAR' 
 AND MONTH = '$V_PARMONTH' 
 AND DAY = '$V_PARDAY' 
 AND CREATE_TIME LIKE '$V_YESTERDAY%'
 GROUP BY AREA 
 GROUPING SETS (AREA,
                ())
) A
LEFT OUTER JOIN
(SELECT CASE WHEN AREA is NULL THEN '10000' ELSE AREA END AREA, 
        COUNT(DISTINCT PHONE) PHONENUM,
        SUM(CNT_ITEMS) CNT_ITEMS_NUM,
        ROUND(SUM(CNT_ITEMS)/COUNT(DISTINCT PHONE),3) CNT_ITEMS_RATE,
        SUM(LEFT_ITEMS) LEFT_ITEMS_NUM 
 FROM PDW.WX_R_LIST_INFO 
 WHERE YEAR = '$V_PARYEAR' 
 AND MONTH = '$V_PARMONTH' 
 AND DAY = '$V_PARDAY' 
 AND CREATE_TIME LIKE '$V_YESTERDAY%' 
 AND CNT_ITEMS != LEFT_ITEMS 
 GROUP BY AREA 
 GROUPING SETS (AREA,
                ())
) B
ON (A.AREA=B.AREA)
LEFT OUTER JOIN 
(SELECT CASE WHEN AREA is NULL THEN '10000' ELSE AREA END AREA,
        COUNT(DISTINCT PHONE) PHONENUM,
        SUM(CNT_ITEMS) CNT_ITEMS_NUM 
 FROM PDW.WX_R_LIST_INFO 
 WHERE YEAR = '$V_PARYEAR' 
 AND MONTH = '$V_PARMONTH' 
 AND DAY = '$V_PARDAY' 
 AND CREATE_TIME LIKE '$V_YESTERDAY%' 
 AND CNT_ITEMS = LEFT_ITEMS 
 GROUP BY AREA 
 GROUPING SETS (AREA,
                ())
) C 
ON (A.AREA = C.AREA)
LEFT OUTER JOIN
(SELECT CASE WHEN E.AREA is NULL THEN '10000' ELSE E.AREA END AREA,
       COUNT(DISTINCT E.PHONE) PHONENUM     
 FROM   
 (SELECT DISTINCT AREA, PHONE 
  FROM PDW.WX_R_LIST_INFO 
  WHERE YEAR='$V_PARYEAR'
  AND MONTH='$V_PARMONTH'
  AND DAY='$V_PARDAY'
  AND CNT_ITEMS != LEFT_ITEMS
  AND CREATE_TIME LIKE '$V_YESTERDAY%'
 ) E
 LEFT OUTER JOIN 
 (SELECT DISTINCT AREA,PHONE 
  FROM PDW.WX_R_LIST_INFO 
  WHERE  CONCAT(YEAR,MONTH,DAY) < '$V_PARYESTERDAY'
  AND  CNT_ITEMS != LEFT_ITEMS
 ) F 
 ON ( E.PHONE = F.PHONE AND E.AREA = F.AREA)  
 WHERE  F.PHONE IS NULL 
 GROUP BY E.AREA 
 GROUPING SETS (E.AREA,
                ())
) D 
ON (A.AREA = D.AREA)
;"

/home/xiaoju/hadoop-1.0.4/bin/hadoop fs -touchz /user/xiaoju/data/bi/app/wechat_senditem_day/$V_PARYEAR/$V_PARMONTH/$V_PARDAY/_SUCCESS
