#function description: 
#procedure name: p_dm_passengerregandcall
#creator:MARS
#created:
#!/bin/bash
#today date
V_DATE=$1
#
if [ -z ${V_DATE} ];then
        V_DATE=`date +%Y-%m-%d`
fi
#yesterday data partition
V_PARYEAR=`date --date="$V_DATE-1 day" +%Y`
V_PARMONTH=`date --date="$V_DATE-1 day" +%m`
V_PARDAY=`date --date="$V_DATE-1 day" +%d`
V_PARYESTERDAY=`date --date="$V_DATE-1 day" +%Y%m%d`
#today,yesterday,7 day  ago,30 days ago,2 days ago  date
V_TODAY=`date -d $V_DATE "+%Y-%m-%d"`
V_YESTERDAY=`date --date="$V_DATE-1 day" +%Y-%m-%d`
V_7DAYS=`date --date="$V_DATE-7 day" +%Y-%m-%d`
V_WEEK=`date --date="$V_DATE-7 day" +%Y-%m-%d`
V_THREEWEEKS=`date --date="$V_DATE-21 day" +%Y-%m-%d`
V_THREEMONTHS=`date --date="$V_DATE-90 day" +%Y-%m-%d`
V_SIXMONTHS=`date --date="$V_DATE-180 day" +%Y-%m-%d`
V_15DAYS=`date --date="$V_DATE-15 day" +%Y-%m-%d`
V_30DAYS=`date --date="$V_DATE-30 day" +%Y-%m-%d`
V_TWODAYS=`date --date="$V_DATE-2 day" +%Y-%m-%d`
#30 days ago, 2 days ago data partition 
V_PAR7DAYS=`date --date="$V_DATE-7 day" +%Y%m%d`
V_PAR15DAYS=`date --date="$V_DATE-15 day" +%Y%m%d`
V_PAR30DAYS=`date --date="$V_DATE-30 day" +%Y%m%d`
V_PAR2DAYS=`date --date="$V_DATE-2 day" +%Y%m%d`
V_PAR2DAYSYEAR=`date --date="$V_DATE-2 day" +%Y`
V_PAR2DAYSMONTH=`date --date="$V_DATE-2 day" +%m`
V_PAR2DAYSDAY=`date --date="$V_DATE-2 day" +%d`
/home/xiaoju/hive-0.10.0/bin/hive -e"use app;
INSERT OVERWRITE TABLE PASSENGERREGANDCALL PARTITION(YEAR='$V_PARYEAR',MONTH='$V_PARMONTH',DAY='$V_PARDAY')
SELECT  0,
	    '$V_YESTERDAY',
		M.AREA,
		M.CHANNEL,
		(CASE WHEN A.PASSENGERTOTAL IS NOT NULL THEN CAST(A.PASSENGERTOTAL AS INT) ELSE 0 END) PASSENGERTOTAL,
		(CASE WHEN C.NEWPASSENGER IS NOT NULL THEN CAST(C.NEWPASSENGER AS INT) ELSE 0 END) NEWPASSENGER,
		(CASE WHEN B.NEW_PASS_CALL_NUM IS NOT NULL THEN CAST(B.NEW_PASS_CALL_NUM AS INT) ELSE 0 END) NEW_PASS_CALL_NUM
  FROM  PDW.PASSENGER_AREA_CHANNEL M
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CAST(CHANNEL AS INT) END) CHANNEL,
	   PASSENGERTOTAL
  FROM (SELECT AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
						ELSE 2 
					END) CHANNEL,
			   COUNT(PID) PASSENGERTOTAL
		  FROM PDW.PASSENGER
		 WHERE YEAR='$V_PARYEAR'
		   AND MONTH='$V_PARMONTH'
		   AND DAY='$V_PARDAY'
		GROUP BY AREA, (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
							WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
							WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
							WHEN CHANNEL = 1101 THEN 5
							WHEN CHANNEL = 1102 THEN 6
							WHEN CHANNEL >= 10000 THEN 8
							WHEN CHANNEL >= 1000 THEN 7
							ELSE 2 
							END)
		GROUPING SETS ( AREA,
						(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END)),
						())
		) W
) A
ON(M.AREA=A.AREA AND M.CHANNEL=A.CHANNEL)
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CAST(CHANNEL AS INT) END) CHANNEL,
		NEW_PASS_CALL_NUM
  FROM (SELECT AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
						ELSE 2 
					END) CHANNEL,
				COUNT(A.PID) NEW_PASS_CALL_NUM
		  FROM PDW.PASSENGER A
		JOIN (SELECT DISTINCT PASSENGERID
				   FROM PDW.DW_ORDER
				  WHERE YEAR='$V_PARYEAR'
					AND MONTH='$V_PARMONTH'
					AND DAY='$V_PARDAY'
				) B
		 ON (A.YEAR='$V_PARYEAR'
			 AND A.MONTH='$V_PARMONTH' 
			 AND A.DAY='$V_PARDAY'
			 AND A.REGTIME >='$V_YESTERDAY' AND A.REGTIME <'$V_TODAY' AND A.STATUS = 0
			 AND A.PID=B.PASSENGERID) 
		GROUP BY AREA, (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
							WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
							WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
							WHEN CHANNEL = 1101 THEN 5
							WHEN CHANNEL = 1102 THEN 6
							WHEN CHANNEL >= 10000 THEN 8
							WHEN CHANNEL >= 1000 THEN 7
							ELSE 2 
							END)
		GROUPING SETS ( AREA,
						(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END)),
						())
		) W
) B
ON(M.AREA=B.AREA AND M.CHANNEL=B.CHANNEL)
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CAST(CHANNEL AS INT) END) CHANNEL,
	   NEWPASSENGER
  FROM (SELECT AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
						ELSE 2 
					END) CHANNEL,
			   COUNT(PID) NEWPASSENGER
		  FROM PDW.PASSENGER
		 WHERE YEAR='$V_PARYEAR'
		   AND MONTH='$V_PARMONTH'
		   AND DAY='$V_PARDAY'
		   AND REGTIME >='$V_YESTERDAY' 
		   AND REGTIME <'$V_TODAY' 
		   AND STATUS = 0
		GROUP BY AREA, (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
							WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
							WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
							WHEN CHANNEL = 1101 THEN 5
							WHEN CHANNEL = 1102 THEN 6
							WHEN CHANNEL >= 10000 THEN 8
							WHEN CHANNEL >= 1000 THEN 7
							ELSE 2 
							END)
		GROUPING SETS ( AREA,
						(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END)),
						())
		) W
) C
ON(M.AREA=C.AREA AND M.CHANNEL=C.CHANNEL)
;"
/home/xiaoju/hadoop-1.0.4/bin/hadoop fs -touchz /user/xiaoju/data/bi/app/passengerregandcall/$V_PARYEAR/$V_PARMONTH/$V_PARDAY/_SUCCESS