#!/bin/sh

begdate='2013-12-23'
enddate='2014-01-06'

for(( i=0; ; i++ ));do
        
    if [[ ${end} = ${enddate} ]];then
        break;
    fi

    end=`date +%Y-%m-%d -d "+${i}days ${begdate}"`
    #echo $end
    #sh staticstic_driver_sqoop_import.sh ${end}
    sh spam_order_sqoop_import.sh ${end}
    sh order_comment_sqoop_import.sh ${end}
    sh order_sqoop_import.sh ${end}
done
