#function description: 
#procedure name: P_DM_orderday
#creator:MARS
#created:
#!/bin/bash
#today date
V_DATE=$1

if [ -z ${V_DATE} ];then
        V_DATE=`date +%Y-%m-%d`
fi

#yesterday data partition
V_PARYEAR=`date --date="$V_DATE-1 day" +%Y`
V_PARMONTH=`date --date="$V_DATE-1 day" +%m`
V_PARDAY=`date --date="$V_DATE-1 day" +%d`
V_PARYESTERDAY=`date --date="$V_DATE-1 day" +%Y%m%d`
#today,yesterday,7 day  ago,30 days ago,2 days ago  date
V_TODAY=`date -d $V_DATE "+%Y-%m-%d"`
V_YESTERDAY=`date --date="$V_DATE-1 day" +%Y-%m-%d`
V_7DAYS=`date --date="$V_DATE-7 day" +%Y-%m-%d`
V_WEEK=`date --date="$V_DATE-7 day" +%Y-%m-%d`
V_THREEWEEKS=`date --date="$V_DATE-21 day" +%Y-%m-%d`
V_THREEMONTHS=`date --date="$V_DATE-90 day" +%Y-%m-%d`
V_SIXMONTHS=`date --date="$V_DATE-180 day" +%Y-%m-%d`
V_15DAYS=`date --date="$V_DATE-15 day" +%Y-%m-%d`
V_30DAYS=`date --date="$V_DATE-30 day" +%Y-%m-%d`
V_TWODAYS=`date --date="$V_DATE-2 day" +%Y-%m-%d`
#30 days ago, 2 days ago data partition 
V_PAR7DAYS=`date --date="$V_DATE-7 day" +%Y%m%d`
V_PAR15DAYS=`date --date="$V_DATE-15 day" +%Y%m%d`
V_PAR30DAYS=`date --date="$V_DATE-30 day" +%Y%m%d`
V_PAR2DAYS=`date --date="$V_DATE-2 day" +%Y%m%d`
# (STATID                  INT,
# STATDATE          STRING,
# area                     	            INT           ,
# channel                  	            INT           ,
# orderCnt                 	            INT           ,
# orderAnswerCnt           	            INT           ,
# orderSuccCnt             	            INT           ,
# orderSuccRate            	            FLOAT         ,
# yesterdayOrderSuccCnt    	            INT           ,
# yesterdayPureOrderSuccCnt	            INT  
# )
/home/xiaoju/hive-0.10.0/bin/hive -e"use app;
INSERT OVERWRITE TABLE ORDERDAY PARTITION(YEAR='$V_PARYEAR',MONTH='$V_PARMONTH',DAY='$V_PARDAY')
SELECT 0,
       '$V_YESTERDAY',
       M.AREA,
	   M.CHANNEL,
	   (CASE WHEN A.ORDERCNT IS NULL THEN 0 ELSE CAST(A.ORDERCNT AS INT) END),
	   (CASE WHEN A.ORDERANSWERCNT IS NULL THEN 0 ELSE CAST(A.ORDERANSWERCNT AS INT) END),
	   (CASE WHEN A.ORDERSUCCCNT IS NULL THEN 0 ELSE CAST(A.ORDERSUCCCNT AS INT) END),
	   (CASE WHEN A.ORDERSUCCRATE IS NULL THEN 0.000 ELSE A.ORDERSUCCRATE END),
	   (CASE WHEN B.YESTERDAYORDERSUCCCNT IS NULL THEN 0 ELSE CAST(B.YESTERDAYORDERSUCCCNT AS INT) END),
	   (CASE WHEN C.YESTERDAYPUREORDERSUCCCNT IS NULL THEN 0 ELSE CAST(C.YESTERDAYPUREORDERSUCCCNT AS INT) END)
  FROM PDW.PASSENGER_AREA_CHANNEL M
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CHANNEL END) CHANNEL,
	   ORDERCNT,
	   ORDERANSWERCNT,
	   ORDERSUCCCNT,
	   ORDERSUCCRATE
  FROM (SELECT AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3 
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END) CHANNEL,
			  COUNT(*)  ORDERCNT,
			  SUM(CASE WHEN DRIVERID != 0 THEN 1
					ELSE 0
				   END) ORDERANSWERCNT,
			  SUM(CASE WHEN STATUS > 0 AND STATUS < 4 THEN 1
					ELSE 0
					END) ORDERSUCCCNT,
			  (CASE WHEN COUNT(*) <>0 THEN ROUND(SUM(CASE WHEN STATUS > 0 AND STATUS < 4 THEN 1
					ELSE 0
					END)/CAST(COUNT(*) AS FLOAT),3)  
				 ELSE 0.00 END) ORDERSUCCRATE
		 FROM PDW.DW_ORDER
		WHERE YEAR='$V_PARYEAR'
		  AND MONTH='$V_PARMONTH'
		  AND DAY='$V_PARDAY'
		  AND CREATETIME >= '$V_YESTERDAY' 
		  AND CREATETIME < '$V_TODAY'
                   AND AREA IS NOT NULL
		GROUP BY AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
							WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
							WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
							WHEN CHANNEL = 1101 THEN 5
							WHEN CHANNEL = 1102 THEN 6
							WHEN CHANNEL >= 10000 THEN 8
							WHEN CHANNEL >= 1000 THEN 7
							ELSE 2 
							END)
		GROUPING SETS (AREA,
					   (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
								WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
								WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
								WHEN CHANNEL = 1101 THEN 5
								WHEN CHANNEL = 1102 THEN 6
								WHEN CHANNEL >= 10000 THEN 8
								WHEN CHANNEL >= 1000 THEN 7
								ELSE 2 
								END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
								WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
								WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
								WHEN CHANNEL = 1101 THEN 5
								WHEN CHANNEL = 1102 THEN 6
								WHEN CHANNEL >= 10000 THEN 8
								WHEN CHANNEL >= 1000 THEN 7
								ELSE 2 
								END)),
						())
		) D
) A
ON(M.AREA=A.AREA AND M.CHANNEL=A.CHANNEL)
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CHANNEL END) CHANNEL,
	   YESTERDAYORDERSUCCCNT
  FROM (SELECT AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END)  CHANNEL,
			  COUNT(*)  YESTERDAYORDERSUCCCNT 
		 FROM PDW.DW_ORDER 
		WHERE CONCAT(YEAR,MONTH,DAY) >= '$V_PAR2DAYS'
		  AND CONCAT(YEAR,MONTH,DAY) < '$V_PARYESTERDAY'
		  AND CREATETIME >= '$V_TWODAYS' 
		  AND CREATETIME < '$V_YESTERDAY'
		  AND STATUS > 0 
		  AND STATUS < 4
                   AND AREA IS NOT NULL
		GROUP BY  AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END)
		GROUPING SETS (AREA,
					   (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
								WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
								WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
								WHEN CHANNEL = 1101 THEN 5
								WHEN CHANNEL = 1102 THEN 6
								WHEN CHANNEL >= 10000 THEN 8
								WHEN CHANNEL >= 1000 THEN 7
								ELSE 2 
								END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
								WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
								WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
								WHEN CHANNEL = 1101 THEN 5
								WHEN CHANNEL = 1102 THEN 6
								WHEN CHANNEL >= 10000 THEN 8
								WHEN CHANNEL >= 1000 THEN 7
								ELSE 2 
								END)),
						())
	    ) D
) B
ON(M.AREA=B.AREA AND M.CHANNEL=B.CHANNEL)
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CHANNEL END) CHANNEL,
	    YESTERDAYPUREORDERSUCCCNT
  FROM  (SELECT AREA, 
					  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
							WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
							WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
							WHEN CHANNEL = 1101 THEN 5
							WHEN CHANNEL = 1102 THEN 6
							WHEN CHANNEL >= 10000 THEN 8
							WHEN CHANNEL >= 1000 THEN 7
							ELSE 2 
							END) CHANNEL,
					   COUNT(*) YESTERDAYPUREORDERSUCCCNT 
				 FROM (SELECT  QQ.*
					     FROM (SELECT A.*
								 FROM (SELECT *
										 FROM PDW.DW_ORDER
										WHERE CONCAT(YEAR,MONTH,DAY) >= '$V_PAR2DAYS'
				  						AND CONCAT(YEAR,MONTH,DAY) < '$V_PARYESTERDAY'
										AND CREATETIME >= '$V_TWODAYS' 
										AND CREATETIME < '$V_YESTERDAY'  
										AND STATUS > 0 
										AND STATUS < 4
										) A
								LEFT OUTER JOIN
									 (SELECT DISTINCT  ORDERID
									   FROM PDW.SPAM_ORDER ) B
								  ON (A.ORDERID=B.ORDERID)
								WHERE B.ORDERID IS NULL
							   ) QQ
					    LEFT OUTER JOIN
							(
								SELECT DISTINCT OID
								  FROM PDW.ORDER_COMMENT 
								 WHERE DCOMPLAINTTYPE>0 
									OR PCOMPLAINTTYPE>0 
							) C
						ON(QQ.ORDERID = C.OID)
						WHERE C.OID IS NULL
						) Z
				GROUP BY AREA, 
					  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
							WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
							WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
							WHEN CHANNEL = 1101 THEN 5
							WHEN CHANNEL = 1102 THEN 6
							WHEN CHANNEL >= 10000 THEN 8
							WHEN CHANNEL >= 1000 THEN 7
							ELSE 2 
							END) 
				GROUPING SETS (AREA,
					   (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
								WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
								WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
								WHEN CHANNEL = 1101 THEN 5
								WHEN CHANNEL = 1102 THEN 6
								WHEN CHANNEL >= 10000 THEN 8
								WHEN CHANNEL >= 1000 THEN 7
								ELSE 2 
								END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
								WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
								WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
								WHEN CHANNEL = 1101 THEN 5
								WHEN CHANNEL = 1102 THEN 6
								WHEN CHANNEL >= 10000 THEN 8
								WHEN CHANNEL >= 1000 THEN 7
								ELSE 2 
								END)),
						())
		) D
) C
ON(M.AREA=C.AREA AND M.CHANNEL=C.CHANNEL)
;"
/home/xiaoju/hadoop-1.0.4/bin/hadoop fs -touchz /user/xiaoju/data/bi/app/orderday/$V_PARYEAR/$V_PARMONTH/$V_PARDAY/_SUCCESS