#function description:
# wx lj  stat

#procedure name: P_DM_wx_lj 
#creator: mayiming
#created:
#!/bin/bash
#today date
V_DATE=$1

#
if [ -z ${V_DATE} ];then
  V_DATE=`date +%Y-%m-%d`
fi

#yesterday data partition
V_PARYEAR=`date --date="$V_DATE-1 day" +%Y`
V_PARMONTH=`date --date="$V_DATE-1 day" +%m`
V_PARDAY=`date --date="$V_DATE-1 day" +%d`

function parseArgs()
{ 
  args=($@)
  arglen=$#

  for (( i=0; i < $arglen; i+=2 )) ;do 
    arg=${args[$i]}

    if [ $arg == "-y" ] ;then
      V_PARYEAR=${args[$i+1]}
    elif [ $arg == "-m" ]   ;then
      V_PARMONTH=${args[$i+1]}
    elif [ $arg == "-d" ]  ;then
      V_PARDAY=${args[$i+1]}
    fi  
  done
}

# Start from here.
parseArgs $@

/home/xiaoju/hive-0.10.0/bin/hive -e"use app;
ALTER TABLE WX_LJ ADD IF NOT EXISTS PARTITION (YEAR = '$V_PARYEAR',MONTH = '$V_PARMONTH',DAY = '$V_PARDAY') LOCATION '$V_PARYEAR/$V_PARMONTH/$V_PARDAY';
INSERT OVERWRITE TABLE WX_LJ PARTITION(YEAR='$V_PARYEAR',MONTH='$V_PARMONTH',DAY='$V_PARDAY')
SELECT 0 STATID,
       '${V_PARYEAR}-${V_PARMONTH}-${V_PARDAY}' STATDATE,
       CASE WHEN AREA IS NULL THEN 10000 ELSE AREA END AREA,
       0 CHANNEL,
       SUM(CASE WHEN COUPONID = 2 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END) LJ_10,
       SUM(CASE WHEN COUPONID = 3 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END) LJ_5,
       SUM(CASE WHEN COUPONID = 4 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END) LJ_15_FRIST,
       SUM(CASE WHEN COUPONID = 5 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END) LJ_12,
       SUM(CASE WHEN COUPONID = 6 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END) LJ_15,
       SUM(CASE WHEN COUPONID = 7 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END) LJ_18,
       SUM(CASE WHEN COUPONID = 8 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END) LJ_20,
       SUM(CASE WHEN COUPONID = 9 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END) LJ_8,
       SUM(CASE WHEN COUPONID = 10 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END) LJ_6,
       ROUND(SUM(CASE WHEN COUPONID = 2 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END)/SUM(ORDER_NUM),3) LJ_10_RATE,
       ROUND(SUM(CASE WHEN COUPONID = 3 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END)/SUM(ORDER_NUM),3) LJ_5_RATE,
       ROUND(SUM(CASE WHEN COUPONID = 4 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END)/SUM(ORDER_NUM),3) LJ_15_FIRST_RATE,
       ROUND(SUM(CASE WHEN COUPONID = 5 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END)/SUM(ORDER_NUM),3) LJ_12_RATE,
       ROUND(SUM(CASE WHEN COUPONID = 6 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END)/SUM(ORDER_NUM),3) LJ_15_RATE,
       ROUND(SUM(CASE WHEN COUPONID = 7 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END)/SUM(ORDER_NUM),3) LJ_18_RATE,
       ROUND(SUM(CASE WHEN COUPONID = 8 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END)/SUM(ORDER_NUM),3) LJ_20_RATE,
       ROUND(SUM(CASE WHEN COUPONID = 9 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END)/SUM(ORDER_NUM),3) LJ_8_RATE,
       ROUND(SUM(CASE WHEN COUPONID = 10 THEN ORDER_NUM ELSE CAST('0' AS BIGINT) END)/SUM(ORDER_NUM),3) LJ_6_RATE 
FROM 
(SELECT AREA,
        CASE WHEN COUPONID >1 AND COUPONID < 11 THEN COUPONID ELSE -1 END COUPONID,
        COUNT(DISTINCT ORDERID) ORDER_NUM
 FROM PDW.WX_DIDI_TRANSACTION 
 WHERE YEAR ='$V_PARYEAR' 
 AND MONTH ='$V_PARMONTH' 
 AND DAY = '$V_PARDAY' 
 AND STATUS = 1 
 AND TRANS_TYPE = 1 
 GROUP BY AREA,
          CASE WHEN COUPONID >1 AND COUPONID < 11 THEN COUPONID ELSE -1 END 
) A
GROUP BY AREA
GROUPING SETS (AREA,
                 ())
;"

/home/xiaoju/hadoop-1.0.4/bin/hadoop fs -touchz /user/xiaoju/data/bi/app/wx_lj/$V_PARYEAR/$V_PARMONTH/$V_PARDAY/_SUCCESS
