#function description: 
#procedure name: P_DM_passengerorderhistory
#creator:MARS
#created:
#!/bin/bash
#today date
V_DATE=$1

if [ -z ${V_DATE} ];then
        V_DATE=`date +%Y-%m-%d`
fi
#yesterday data partition
V_PARYEAR=`date --date="$V_DATE-1 day" +%Y`
V_PARMONTH=`date --date="$V_DATE-1 day" +%m`
V_PARDAY=`date --date="$V_DATE-1 day" +%d`
V_PARYESTERDAY=`date --date="$V_DATE-1 day" +%Y%m%d`
#today,yesterday,7 day  ago,30 days ago,2 days ago  date
V_TODAY=`date -d $V_DATE "+%Y-%m-%d"`
V_YESTERDAY=`date --date="$V_DATE-1 day" +%Y-%m-%d`
V_7DAYS=`date --date="$V_DATE-7 day" +%Y-%m-%d`
V_WEEK=`date --date="$V_DATE-7 day" +%Y-%m-%d`
V_THREEWEEKS=`date --date="$V_DATE-21 day" +%Y-%m-%d`
V_THREEMONTHS=`date --date="$V_DATE-90 day" +%Y-%m-%d`
V_SIXMONTHS=`date --date="$V_DATE-180 day" +%Y-%m-%d`
V_15DAYS=`date --date="$V_DATE-15 day" +%Y-%m-%d`
V_30DAYS=`date --date="$V_DATE-30 day" +%Y-%m-%d`
V_TWODAYS=`date --date="$V_DATE-2 day" +%Y-%m-%d`
#30 days ago, 2 days ago data partition 
V_PAR7DAYS=`date --date="$V_DATE-7 day" +%Y%m%d`
V_PAR15DAYS=`date --date="$V_DATE-15 day" +%Y%m%d`
V_PAR30DAYS=`date --date="$V_DATE-30 day" +%Y%m%d`
V_PAR2DAYS=`date --date="$V_DATE-2 day" +%Y%m%d`
V_PAR2DAYSYEAR=`date --date="$V_DATE-2 day" +%Y`
V_PAR2DAYSMONTH=`date --date="$V_DATE-2 day" +%m`
V_PAR2DAYSDAY=`date --date="$V_DATE-2 day" +%d`
# (STATID                  INT,
#  STATDATE          STRING,
# area                          	             INT   ,
# channel                       	             INT   ,
# weekSuccOrderMoreThanThreeCnt 	             INT   ,
# weekNoOrderCnt                	             INT   ,
# halfMonthNoOrderCnt           	             INT   ,
# monthNoOrderCnt               	             INT	
# )
/home/xiaoju/hive-0.10.0/bin/hive -e"use app;
INSERT OVERWRITE TABLE PASSENGERORDERHISTORY PARTITION(YEAR='$V_PARYEAR',MONTH='$V_PARMONTH',DAY='$V_PARDAY')
SELECT  0,
	    '$V_YESTERDAY',
		M.AREA,
		M.CHANNEL,
		(CASE WHEN A.WEEKSUCCORDERMORETHANTHREECNT IS NULL THEN 0 ELSE CAST(A.WEEKSUCCORDERMORETHANTHREECNT AS INT) END),
		(CASE WHEN C.TOTALREGCNT IS NOT NULL AND  B.WEEKCALLPASSENGERCNT IS NOT NULL THEN C.TOTALREGCNT - B.WEEKCALLPASSENGERCNT 
			  WHEN C.TOTALREGCNT IS NOT NULL AND  B.WEEKCALLPASSENGERCNT IS NULL THEN CAST(C.TOTALREGCNT AS BIGINT) - 0
			  WHEN C.TOTALREGCNT IS NULL AND  B.WEEKCALLPASSENGERCNT IS NOT NULL THEN 0 - CAST(B.WEEKCALLPASSENGERCNT AS BIGINT)
			  ELSE CAST(0 AS BIGINT)
			  END) WEEKNOORDERCNT,
		(CASE WHEN C.TOTALREGCNT IS NOT NULL AND D.HALFMONTHCALLPASSENGERCNT IS NOT NULL THEN C.TOTALREGCNT - D.HALFMONTHCALLPASSENGERCNT    
		      WHEN C.TOTALREGCNT IS NOT NULL AND D.HALFMONTHCALLPASSENGERCNT IS NULL THEN CAST(C.TOTALREGCNT AS BIGINT) - 0
			  WHEN C.TOTALREGCNT IS NULL AND D.HALFMONTHCALLPASSENGERCNT IS NOT NULL THEN  0 - CAST(D.HALFMONTHCALLPASSENGERCNT AS BIGINT)
		      ELSE CAST(0 AS BIGINT)
		     END) HALFMONTHNOORDERCNT,
		(CASE WHEN  C.TOTALREGCNT IS NOT NULL AND E.MONTHCALLPASSENGERCNT IS NOT NULL THEN C.TOTALREGCNT - E.MONTHCALLPASSENGERCNT  
              WHEN  C.TOTALREGCNT IS NOT NULL AND E.MONTHCALLPASSENGERCNT IS NULL THEN CAST(C.TOTALREGCNT AS BIGINT) - 0
			  WHEN  C.TOTALREGCNT IS NULL AND E.MONTHCALLPASSENGERCNT IS NOT NULL THEN 0 - E.MONTHCALLPASSENGERCNT 
		      ELSE CAST(0 AS BIGINT)
			  END) MONTHNOORDERCNT
  FROM  PDW.PASSENGER_AREA_CHANNEL M
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CHANNEL END) CHANNEL,
	   WEEKSUCCORDERMORETHANTHREECNT
  FROM (SELECT AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END)  CHANNEL, 
			  COUNT(*) WEEKSUCCORDERMORETHANTHREECNT
		FROM (SELECT PASSENGERID,
					 COUNT(*)  ORDERCNT 
				FROM PDW.DW_ORDER 
				WHERE CONCAT(YEAR,MONTH,DAY) >= '$V_PAR7DAYS'
				  AND CONCAT(YEAR,MONTH,DAY) <= '$V_PAR2DAYS'
				  AND CREATETIME >= '$V_7DAYS' 
				  AND CREATETIME < '$V_TODAY' 
					GROUP BY PASSENGERID
			  ) D 
		JOIN  (SELECT PID,
		              AREA,
					  CHANNEL
			     FROM PDW.PASSENGER
				WHERE YEAR='$V_PARYEAR'
				  AND MONTH='$V_PARMONTH'
				  AND DAY='$V_PARDAY'
                                   AND AREA IS NOT NULL
		       ) Q
		ON (D.ORDERCNT >= 3 AND D.PASSENGERID=Q.PID)
		GROUP BY AREA, (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
							WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
							WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
							WHEN CHANNEL = 1101 THEN 5
							WHEN CHANNEL = 1102 THEN 6
							WHEN CHANNEL >= 10000 THEN 8
							WHEN CHANNEL >= 1000 THEN 7
							ELSE 2 
							END)
		GROUPING SETS ( AREA,
						(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END)),
						())
       ) D
) A
ON(M.AREA=A.AREA AND M.CHANNEL=A.CHANNEL)
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CHANNEL END) CHANNEL,
	   WEEKCALLPASSENGERCNT
  FROM (SELECT AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END) CHANNEL,
				COUNT(*) WEEKCALLPASSENGERCNT 
			FROM (SELECT PASSENGERID,
					   COUNT(*)  ORDERCNT 
				  FROM PDW.DW_ORDER
				 WHERE CONCAT(YEAR,MONTH,DAY) >= '$V_PAR7DAYS'
				   AND CONCAT(YEAR,MONTH,DAY) <= '$V_PAR2DAYS'
				   AND CREATETIME >= '$V_7DAYS' 
				   AND CREATETIME < '$V_TODAY'
				GROUP BY PASSENGERID)  D 
			JOIN  (SELECT PID,
						  AREA,
						  CHANNEL
					 FROM PDW.PASSENGER
					WHERE YEAR='$V_PARYEAR'
					  AND MONTH='$V_PARMONTH'
					  AND DAY='$V_PARDAY'
                                           AND AREA IS NOT NULL
				   ) Q
		ON (D.ORDERCNT = 0 AND D.PASSENGERID=Q.PID)
		GROUP BY AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END)
		GROUPING SETS ( AREA,
						(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END)),
						())
        ) D
) B
ON(M.AREA=B.AREA AND M.CHANNEL=B.CHANNEL)
LEFT OUTER JOIN
(
SELECT AREA,
	   CHANNEL,
	   TOTALREGCNT
  FROM APP.PASSENGERREG
 WHERE YEAR='$V_PARYEAR'
   AND MONTH='$V_PARMONTH'
   AND DAY='$V_PARDAY'
) C
ON(M.AREA=C.AREA AND M.CHANNEL=C.CHANNEL)
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CHANNEL END) CHANNEL,
	   HALFMONTHCALLPASSENGERCNT
  FROM (SELECT AREA, 
				  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
						WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
						WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
						WHEN CHANNEL = 1101 THEN 5
						WHEN CHANNEL = 1102 THEN 6
						WHEN CHANNEL >= 10000 THEN 8
						WHEN CHANNEL >= 1000 THEN 7
						ELSE 2 
						END)  CHANNEL,
				   COUNT(*)  HALFMONTHCALLPASSENGERCNT 
			 FROM (SELECT PASSENGERID,
						 COUNT(*)  ORDERCNT 
					FROM PDW.DW_ORDER
			WHERE CONCAT(YEAR,MONTH,DAY) >= '$V_PAR15DAYS'
					AND CONCAT(YEAR,MONTH,DAY) <= '$V_PAR2DAYS'
					AND CREATETIME >= '$V_15DAYS' 
					AND CREATETIME < '$V_TODAY' 
				   GROUP BY PASSENGERID) D 
			JOIN  (SELECT PID,
						  AREA,
						  CHANNEL
					 FROM PDW.PASSENGER
					WHERE YEAR='$V_PARYEAR'
					  AND MONTH='$V_PARMONTH'
					  AND DAY='$V_PARDAY'
                                           AND AREA IS NOT NULL
				   ) Q
            ON (D.ORDERCNT > 0 AND D.PASSENGERID=Q.PID)				   
			GROUP BY AREA, 
				  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
						WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
						WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
						WHEN CHANNEL = 1101 THEN 5
						WHEN CHANNEL = 1102 THEN 6
						WHEN CHANNEL >= 10000 THEN 8
						WHEN CHANNEL >= 1000 THEN 7
						ELSE 2 
						END)
		 GROUPING SETS ( AREA,
						(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END)),
						())	
        ) W						
) D
ON(M.AREA=D.AREA AND M.CHANNEL=D.CHANNEL)
LEFT OUTER JOIN
(
SELECT (CASE WHEN AREA IS NULL THEN 10000 ELSE CAST(AREA AS INT) END) AREA,
       (CASE WHEN CHANNEL IS NULL THEN 0 ELSE CHANNEL END) CHANNEL,
	    MONTHCALLPASSENGERCNT
  FROM (SELECT AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END) CHANNEL,
			  COUNT(*)   MONTHCALLPASSENGERCNT
		FROM (SELECT PASSENGERID,
					 COUNT(*)  ORDERCNT 
				FROM PDW.DW_ORDER 
				WHERE CONCAT(YEAR,MONTH,DAY) >= '$V_PAR30DAYS'
				AND CONCAT(YEAR,MONTH,DAY) <= '$V_PAR2DAYS'
				AND CREATETIME >= '$V_30DAYS' 
				AND CREATETIME < '$V_TODAY' 
				GROUP BY PASSENGERID
				) D
			JOIN  (SELECT PID,
						  AREA,
						  CHANNEL
					 FROM PDW.PASSENGER
					WHERE YEAR='$V_PARYEAR'
					  AND MONTH='$V_PARMONTH'
					  AND DAY='$V_PARDAY'
                                           AND AREA IS NOT NULL
				   ) Q
            ON (D.ORDERCNT > 0 AND D.PASSENGERID=Q.PID)					
		GROUP BY AREA, 
			  (CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
					WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
					WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
					WHEN CHANNEL = 1101 THEN 5
					WHEN CHANNEL = 1102 THEN 6
					WHEN CHANNEL >= 10000 THEN 8
					WHEN CHANNEL >= 1000 THEN 7
					ELSE 2 
					END) 
		 GROUPING SETS ( AREA,
						(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END),
						(AREA,(CASE WHEN CHANNEL=48 OR CHANNEL=106 OR CHANNEL=1105 THEN 4
												WHEN CHANNEL >= 101 AND CHANNEL <= 111 THEN 1 
												WHEN CHANNEL >= 150 AND CHANNEL <= 151 THEN 3
												WHEN CHANNEL = 1101 THEN 5
												WHEN CHANNEL = 1102 THEN 6
												WHEN CHANNEL >= 10000 THEN 8
												WHEN CHANNEL >= 1000 THEN 7
												ELSE 2 
												END)),
						())	
		) W
) E
ON(M.AREA=E.AREA AND M.CHANNEL=E.CHANNEL)
;"
/home/xiaoju/hadoop-1.0.4/bin/hadoop fs -touchz /user/xiaoju/data/bi/app/passengerorderhistory/$V_PARYEAR/$V_PARMONTH/$V_PARDAY/_SUCCESS